export const portfolioItemInfo = [
  {
    id: 0,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/strava-clone.png",
    videoValue: "https://www.youtube.com/embed/eYZwQ4xc2kI",
    title: "Strava clone",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 1,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/ipad.png",
    videoValue: "https://www.youtube.com/embed/Myggk_uXFhc",
    title: "iPad with apps",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 2,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/CRUD app with firebase.png",
    videoValue: "https://www.youtube.com/embed/sAgAXU1uqDI",
    title: "CRUD app with firebase",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 3,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/realtime chat.png",
    videoValue: "https://www.youtube.com/embed/rVdubB7xFXw",
    title: "Realtime chat with firebase",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 4,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/inst-clone.png",
    videoValue: "https://www.youtube.com/embed/kLT5asG2-g4",
    title: "Instagram Clone with firebase + next js",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 5,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/expensetracker.png",
    videoValue: "https://www.youtube.com/embed/d6CNkJFAfsE",
    title: "Expense Tracker",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 6,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/movieapp.png",
    videoValue: "https://www.youtube.com/embed/NeJB3aikdL8",
    title: "Movie App",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 7,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/quizgame.png",
    videoValue: "https://www.youtube.com/embed/3fk6PejqwTU",
    title: "Quize Game",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 8,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/weatherApp.png",
    videoValue: "https://www.youtube.com/embed/0wruitMzjjA",
    title: "Weather App",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 9,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "react",
    imgValue: "/img/img-portfolio-react/react-musicplayer-zustand.png",
    videoValue: "https://www.youtube.com/embed/HBy7gA8Cx4s",
    title: "React Music Player + zustand",
    githubValue: "1488",
    whatGroup: "react",
  },
  {
    id: 10,
    jsValue: "js",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-portfolio-js/imgeditor.png",
    videoValue: "https://www.youtube.com/embed/Vvv9XOoIm9w",
    title: "Image editor",
    githubValue: "1488",
    whatGroup: "javascript",
  },
  {
    id: 11,
    jsValue: "js",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-portfolio-js/snake1.png",
    videoValue: "https://www.youtube.com/embed/Eus0MndZYr8",
    title: "Snake game",
    githubValue: "1488",
    whatGroup: "javascript",
  },
  {
    id: 12,
    jsValue: "js",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-portfolio-js/todojs.png",
    videoValue: "https://www.youtube.com/embed/0DaB3wqPIRI",
    title: "ToDo List js",
    githubValue: "1488",
    whatGroup: "javascript",
  },
  {
    id: 13,
    jsValue: "js",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-portfolio-js/music-player.png",
    videoValue: "https://www.youtube.com/embed/ld_q7mW17d0",
    title: "Music Player",
    githubValue: "1488",
    whatGroup: "javascript",
  },
  {
    id: 14,
    jsValue: "js",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-portfolio-js/calculatorjs.png",
    videoValue: "https://www.youtube.com/embed/O5qpIvMG1v0",
    title: "Calculator",
    githubValue: "1488",
    whatGroup: "javascript",
  },
  {
    id: 15,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 1.png",
    videoValue: "https://www.youtube.com/embed/bjlp09nhuHw",
    title: "Checkers site",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 16,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 2.png",
    videoValue: "https://www.youtube.com/embed/SqWH5rzBXKc",
    title: "Blog site",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 17,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 3.png",
    videoValue: "https://www.youtube.com/embed/8ME_9L_tkMc",
    title: "NewProvidence",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 18,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 4.png",
    videoValue: "https://www.youtube.com/embed/NQW4DHy7quk",
    title: "Design Documentation site",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 19,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 5.png",
    videoValue: "https://www.youtube.com/embed/zMjIl2PA4Jc",
    title: "Animation banner",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 20,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 6.png",
    videoValue: "https://www.youtube.com/embed/M_eaQkOtXpA",
    title: "Rozetta web site",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 21,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 7.png",
    videoValue: "https://www.youtube.com/embed/AkmJtTAKFP8",
    title: "Architecture web site",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 22,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 8.png",
    videoValue: "https://www.youtube.com/embed/pCl-gohBn2s",
    title: "Personal web site",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 23,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 9.png",
    videoValue: "https://www.youtube.com/embed/zjQNNmuUi30",
    title: "Survey web site",
    githubValue: "1488",
    whatGroup: "html",
  },
  {
    id: 24,
    jsValue: "displayNone",
    htmlValue: "html",
    cssValue: "css",
    reactValue: "displayNone",
    imgValue: "/img/img-porfolio-html/html 10.png",
    videoValue: "https://www.youtube.com/embed/WmSXYXjn3Y8",
    title: "Doctor web site",
    githubValue: "1488",
    whatGroup: "html",
  },
];
